# Nome da pipeline
name: Run Basic tests

#Quando ela vai ser executada
on:
  pull_request:
    branches: [main]

jobs: 
  # oque vai ser feito na pipeline
  #só vamos ter um job para rodar os testes
  cypress-run:
    #maquina que sera executada os testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v3
      #Execuçao de configuração do nosso projeto
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: True
        env:
          CYPRES_RECORD_KEY: ${{secrets.CYPRESS_RECORDE_KEY}}

          #Upload do relatorio do mocha
      - name: upload relatorio
        uses: actions/upload-artifact@v3
        with:
          name: Relatorio dos testes e2e
          path: cypress/reports/html